/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cesar.inteligenciaartificial.view;

import com.cesar.inteligenciaartificial.controller.JogoVelhaCtrl;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author cesar
 */
public class JogoVelhaUI extends javax.swing.JFrame {

    /**
     * Creates new form JogoVelhaUI
     */
    private JogoVelhaCtrl controll;
    
    public JogoVelhaUI(JogoVelhaCtrl controll) {
        initComponents();
        this.controll = controll;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        campo1 = new javax.swing.JTextField();
        campo2 = new javax.swing.JTextField();
        campo3 = new javax.swing.JTextField();
        campo4 = new javax.swing.JTextField();
        campo5 = new javax.swing.JTextField();
        campo6 = new javax.swing.JTextField();
        campo7 = new javax.swing.JTextField();
        campo8 = new javax.swing.JTextField();
        campo9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botaoEuComeco = new javax.swing.JButton();
        botaoMaqComecao = new javax.swing.JButton();
        botaoDesistir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Velha (Inteligência Artificial)");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        campo1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        campo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo1.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(campo1, gridBagConstraints);

        campo2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        campo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo2.setText("O");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(campo2, gridBagConstraints);

        campo3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        campo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo3.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(campo3, gridBagConstraints);

        campo4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        campo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo4.setText("O");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(campo4, gridBagConstraints);

        campo5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        campo5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo5.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(campo5, gridBagConstraints);

        campo6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        campo6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo6.setText("O");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(campo6, gridBagConstraints);

        campo7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        campo7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo7.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(campo7, gridBagConstraints);

        campo8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        campo8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo8.setText("O");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(campo8, gridBagConstraints);

        campo9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        campo9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo9.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(campo9, gridBagConstraints);

        jLabel1.setText("Selecione o campo e informe seu símbolo ( X )");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        botaoEuComeco.setText("Eu começo");
        botaoEuComeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEuComecoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(botaoEuComeco, gridBagConstraints);

        botaoMaqComecao.setText("Maq. começa");
        botaoMaqComecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMaqComecaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(botaoMaqComecao, gridBagConstraints);

        botaoDesistir.setText("Eu desisto");
        botaoDesistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesistirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(botaoDesistir, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEuComecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEuComecoActionPerformed
        controll.euComeco();
    }//GEN-LAST:event_botaoEuComecoActionPerformed

    private void botaoMaqComecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMaqComecaoActionPerformed
        controll.maquinaComeca();
    }//GEN-LAST:event_botaoMaqComecaoActionPerformed

    private void botaoDesistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesistirActionPerformed
        controll.euDesisto();
    }//GEN-LAST:event_botaoDesistirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoVelhaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoVelhaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoVelhaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoVelhaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoVelhaUI(null).setVisible(true);
            }
        });
    }

    public JTextField getCampo1() {
        return campo1;
    }

    public JTextField getCampo2() {
        return campo2;
    }

    public JTextField getCampo3() {
        return campo3;
    }

    public JTextField getCampo4() {
        return campo4;
    }

    public JTextField getCampo5() {
        return campo5;
    }

    public JTextField getCampo6() {
        return campo6;
    }

    public JTextField getCampo7() {
        return campo7;
    }

    public JTextField getCampo8() {
        return campo8;
    }

    public JTextField getCampo9() {
        return campo9;
    }

    public JButton getBotaoDesistir() {
        return botaoDesistir;
    }

    public JButton getBotaoEuComeco() {
        return botaoEuComeco;
    }

    public JButton getBotaoMaqComecao() {
        return botaoMaqComecao;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDesistir;
    private javax.swing.JButton botaoEuComeco;
    private javax.swing.JButton botaoMaqComecao;
    private javax.swing.JTextField campo1;
    private javax.swing.JTextField campo2;
    private javax.swing.JTextField campo3;
    private javax.swing.JTextField campo4;
    private javax.swing.JTextField campo5;
    private javax.swing.JTextField campo6;
    private javax.swing.JTextField campo7;
    private javax.swing.JTextField campo8;
    private javax.swing.JTextField campo9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
